"""
Curriculum v2 - Two tracks: RTCDP and Analytics
Run: python seed_curriculum_v2.py
"""
import os, psycopg2
from dotenv import load_dotenv
from pathlib import Path

load_dotenv(Path(__file__).parent.parent / ".env")
DB = os.getenv("DATABASE_URL","postgresql://postgres:nexus123@localhost:5432/nexus")

# ── RTCDP Track (refined from enablement doc) ─────────────────────────────────
RTCDP = {
1: [
  ("Introduction to Platform",
   "Understand how AEP powers an end-to-end customer experience",
   "Log in to AEP, explore the main navigation: Schemas, Datasets, Profiles, Segments, Destinations",
   "2-3 org-relevant AEP use cases written in your own words",
   "Can describe in plain language how AEP enables one real business scenario",
   "A customer experience powered by Experience Platform","3 min"),
  ("Technical Introduction to AEP",
   "Understand AEP core services and how they connect",
   "Click through Schemas, Datasets, Profiles, Identities, Segments, Destinations in AEP UI; map each to a use case",
   "Mapping table: service, purpose, example use case",
   "Can explain in 1-2 sentences what each core service does and why it matters",
   None,None),
  ("AEP Architecture Overview",
   "Understand the high-level data flow: sources to data lake to Profile to activation",
   "Sketch a data flow diagram for one expected use case; annotate with the AEP service at each step",
   "Architecture diagram with service labels at each stage",
   "Reviewer confirms each step (ingest, store, assemble, segment, activate) maps to the right AEP service",
   "Adobe Experience Platform architecture overview","9 min"),
  ("Authenticate and Access AEP APIs",
   "Learn how to authenticate and call AEP APIs using credentials and sandbox context",
   "Open Adobe Developer Console, locate the AEP project, review credentials; perform one GET call (list sandboxes or schemas) using Postman",
   "Working API call with notes on required headers",
   "Can successfully call an AEP API endpoint and explain all required headers",
   None,None),
  ("Introduction to Sandboxes",
   "Understand sandbox types and how to use them safely",
   "Open the Sandboxes view, list available sandboxes (prod, stage, dev, PoC), identify which to use for training",
   "Short sandbox usage guideline: when to use each type",
   "Can correctly state which sandbox to use for practice vs. which not to touch",
   None,None),
  ("Introduction to Real-Time CDP",
   "Explain what RTCDP is and how it differs from a DMP and a CRM",
   "Read the RTCDP overview documentation and answer: What is RTCDP? How does it differ from Audience Manager and a CRM? Why is it built on AEP?",
   "Personal notes on RTCDP differentiation",
   "Can answer the three questions above without slides",
   None,None),
  ("Experience Platform Data Sources",
   "Explain what a data source is in AEP and the types of source connectors available",
   "Explore the Sources catalog in AEP UI; identify at least 3 connector categories",
   "Notes on connector types and ingestion methods",
   "Can define data source and source connector; distinguish batch from streaming ingestion",
   "https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/sources/overview",None),
  ("Experience Platform Governance",
   "Explain the purpose of data governance and how it is applied end-to-end in AEP",
   "Review labels, policies, and marketing action restrictions in AEP; note at least 2 label types and one policy violation scenario",
   "Summary: 2 label types, one policy, what happens on violation",
   "Can explain governance end-to-end: labels, policies, marketing actions, violation enforcement",
   None,None),
  ("Real-Time Customer Profiles",
   "Explain what a Real-Time Customer Profile is and how identities are stitched together",
   "Navigate to Profiles, open an example profile, review the unified timeline, attributes, identities, and related datasets",
   "Profile view familiarity confirmed; able to walk through each section verbally",
   "Can explain what RTCP is; identify key sections of the profile view; describe how data sources contribute",
   "Understanding Real Time Customer Profile","6 min"),
  ("Segmentation Fundamentals",
   "Understand how segmentation sits between Profile and activation; differentiate segmentation modes",
   "Open Segment Builder and explore evaluation types; create one simple batch and one streaming segment",
   "Notes on batch vs streaming with relevant examples; one of each segment created",
   "Can define a segment; distinguish batch vs streaming; translate a use case into segment logic",
   None,None),
  ("Query Service Introduction",
   "Use Query Service to validate and explore ingested data using standard SQL",
   "Run a basic SQL query in Query Service UI against an ingested dataset",
   "Working query with notes on use case and results",
   "Can explain what Query Service is; design a basic validation query; explain how to interpret results",
   None,None),
],
2: [
  ("Ingest Data from Adobe Analytics",
   "Ingest behavioral data from Adobe Analytics into AEP",
   "Configure an Adobe Analytics source connector and dataflow for a report suite; run the initial ingestion",
   "Active Adobe Analytics source connection and running dataflow",
   "Batches complete successfully; Analytics events visible in AEP datasets and profile",
   "Ingest data using the Adobe Analytics source connector","11 min"),
  ("Ingest Data from Audience Manager",
   "Bring Audience Manager traits and segments into RTCDP for activation",
   "Configure Audience Manager source connector, select traits and segments, enable datasets for Profile; let first sync run",
   "Audience Manager source connection with selected traits and segments",
   "AAM traits visible in Segment Builder; sample profiles enriched with AAM data",
   "Ingest data using the Adobe Audience Manager data connector","9 min"),
  ("Ingest Data from Cloud Storage",
   "Import batch files from cloud storage (S3, Blob, GCS, SFTP) into AEP",
   "Create a cloud storage source, map a sample file to XDM schema, run the dataflow",
   "Cloud storage source and dataset populated with ingested records",
   "Batch status = Success; row count in dataset matches source file",
   "Ingest data using Cloud Storage source connectors","7 min"),
  ("Ingest Data from CRM",
   "Onboard CRM customer data into Real-Time CDP",
   "Configure a CRM source, map fields to an XDM Profile schema, enable dataset for Profile; run first dataflow",
   "CRM source connection and Profile-enabled dataset",
   "Customer profiles visible in Profile UI with CRM attributes populated",
   "Ingest data using CRM source connectors","7 min"),
  ("Ingest Data from Databases",
   "Stream or batch-load transactional data from relational databases",
   "Configure a database source (Azure SQL, Snowflake, MySQL, Postgres); create dataflow to XDM schema",
   "Database source connection and dataset with ingested records",
   "Batches succeed; key fields correctly mapped and usable in queries and segments",
   "Ingest data using database source connector","8 min"),
  ("Identity and Identity Graphs",
   "Understand identity namespaces, graphs, and how multiple identities stitch into one profile",
   "Open the Identity UI, review available namespaces, view an identity graph for a sample profile",
   "Notes on identity stitching and namespace types",
   "Can explain what an identity graph is; describe how ECID, email, and CRM ID merge into one profile",
   None,None),
  ("Label, Ingest, and Verify Identity Data",
   "Correctly label identity fields in schemas and verify identity resolution after ingestion",
   "Review a schema with identity labels; ingest sample data; verify identity stitching in Profile UI",
   "Identity-enabled schema confirmed; profile with multiple stitched identities verified",
   "Can identify which fields are marked as identity; verify two profiles with the same email are merged",
   None,None),
],
3: [
  ("Real-Time Customer Profile Core Concepts",
   "Understand core capabilities of Real-Time Customer Profile",
   "Navigate to Profiles, open a profile, review unified timeline, attributes, identities, and related datasets; walk through each section verbally",
   "Profile view familiarity confirmed",
   "Can explain RTCP; identify all key sections; describe how each data source contributes",
   "Understanding Real Time Customer Profile","6 min"),
  ("Profile Overview Diagram",
   "Understand the end-to-end data flow into Profile via the overview diagram",
   "Review the Profile overview diagram; map each element to the actual AEP UI workspace",
   "Annotated diagram mapping each step to an AEP workspace",
   "Can walk through the diagram mapping each step (ingestion, identity, profile, activation) to the corresponding workspace",
   "Real-time customer profile overview diagram","7 min"),
  ("Bring Data into Profile",
   "Enable schemas and datasets so ingested data contributes to Real-Time Customer Profile",
   "Choose a schema, confirm it has an identity and is Profile enabled; enable a corresponding dataset for Profile; ingest sample data",
   "Profile-enabled dataset and sample profiles ingested",
   "Can show an enabled schema and dataset; confirm profiles are created; explain the impact of Profile enablement",
   "Bringing Data into Real-time Customer Profile","2 min"),
  ("Customize Profile View",
   "Configure what appears in the profile details UI",
   "In Profiles Settings, adjust visible attributes, groups, and layout; open a profile to confirm the configuration",
   "Modified profile view showing new attributes or sections",
   "Can demonstrate a modified profile view and explain how to adjust it again",
   None,None),
  ("View Account Profiles",
   "Browse and inspect account-level profiles for B2B use cases",
   "Navigate to Profiles Accounts, search for an account, review account attributes, related people, and activities",
   "Account profile view familiarity confirmed",
   "Can locate an account profile; distinguish account-level vs person-level views; describe key account attributes",
   "Real-time Customer Data Platform Unified Account Profile","4 min"),
  ("Create Merge Policies",
   "Create and manage merge policies that control how Profile data is stitched",
   "Navigate to Profiles Merge Policies, create a new policy with chosen datasets and precedence rules, apply to a test profile",
   "Merge policy configured; test profile shows expected stitched attributes",
   "Can explain the selected merge method and precedence; show how different policies change a test profile",
   "Create a merge policy","5 min"),
  ("Union Schemas",
   "Understand how union schemas are built and used for Profile and segmentation",
   "Open Schemas Union Schemas, select a union schema, inspect contributing XDM classes and how fields roll up",
   "List of contributing schemas and 3-5 key fields expected in segments",
   "Can identify which schemas contribute to a union schema and explain the impact on segmentation",
   "Union Schemas in Experience Platform","3 min"),
],
4: [
  ("Segmentation and Audience Types Overview",
   "Understand RTCDP segmentation concepts: batch, streaming, profile, account, basic, advanced",
   "Open Segments workspace, review evaluation types and statuses; identify 3 existing segments and classify them",
   "Notes on segment types and evaluation modes",
   "Can explain what a segment is, how it is evaluated, and the main segment types in RTCDP",
   "Segments - Segment Builder Overview","10 min"),
  ("Segment Builder UI",
   "Learn the Segment Builder layout: canvas, attributes, events, preview panel",
   "Open Segment Builder, explore the canvas, attribute and events browser, and profile preview; annotate each panel",
   "Annotated screenshot or notes on each panel section",
   "Can point to where to add conditions, where estimates appear, and where profiles are previewed",
   None,None),
  ("Create Basic Attribute Segments",
   "Build profile-based audiences from attributes such as geography, age, and loyalty tier",
   "Create a basic segment using profile attributes only; build and save 2-3 segments with clear names",
   "Saved attribute segments with clear names and visible audience counts",
   "Audience count visible; can articulate the segment logic in plain language",
   "Create Segments","6 min"),
  ("Streaming vs Batch Segmentation",
   "Understand streaming segmentation and when to use it over batch",
   "Review segment evaluation types; create a behavior-based streaming segment",
   "One streaming segment with evaluation type confirmed as Streaming",
   "Evaluation type shows Streaming; can explain latency expectations vs batch",
   None,None),
  ("Content-Based Segments",
   "Target users based on content or product category interactions",
   "Create a segment where users have interacted with a specific product or content type",
   "1-2 content-based segments referencing event-level fields",
   "Preview members look correct; conditions reference correct event fields",
   "Create Content-Based Segments","5 min"),
  ("Conversion Segments",
   "Identify converters and non-converters for marketing and analytics",
   "Create a Converters segment and a Non-Converters segment based on purchase events with time windows",
   "2 conversion segments with correct time logic",
   "Time window correctly applied; business definition matches expectation",
   "Create Conversion Segments","6 min"),
  ("Segments from Existing Segments",
   "Reuse existing segment logic instead of rebuilding from scratch",
   "Create a segment that includes or excludes an existing base segment",
   "1 derived segment based on an existing segment",
   "Can explain the dependency: what happens when the base segment changes",
   "Create Segments from Existing Segments","4 min"),
  ("Dynamic Segments",
   "Use rolling time windows to avoid static dates",
   "Convert an existing segment from fixed dates to dynamic lookback (for example, last 30 days)",
   "1 dynamic segment with relative time window",
   "Can explain the difference between fixed date and rolling window",
   "Create Dynamic Segments","4 min"),
  ("Sequential Segments",
   "Model ordered customer journeys and behaviors",
   "Create a sequential segment (viewed product, added to cart, no purchase) with time constraints",
   "1 sequential segment with valid ordered logic",
   "Sequence logic makes sense; can narrate the journey steps",
   "Create Sequential Segments","8 min"),
  ("Multi-Entity Segments",
   "Use related entities (product, subscription, store) in segment logic",
   "Verify a relationship in the schema, then use related attributes in a segment",
   "1 multi-entity segment returning plausible results",
   "Related attributes are available and segment returns expected members",
   None,None),
  ("B2B Segments",
   "Understand B2B schemas and create account and person-based audiences",
   "Build 1 account segment (industry + revenue) and 1 people segment (job role)",
   "2 B2B segments: one account-level, one person-level",
   "Can describe Account vs Person vs Opportunity audiences and their usage",
   None,None),
  ("Evaluate and Monitor Segment Results",
   "Run, monitor, and interpret segment evaluations",
   "Open segment details, run evaluation if batch, review counts, history, and logs",
   "Evaluation notes for 2-3 segments with expected vs actual counts",
   "Can explain evaluation status, run time, and how to spot anomalies",
   None,None),
  ("Export Segment to Dataset",
   "Land audience data in a dataset for downstream use",
   "Create a dataset and configure export for one segment; verify records",
   "1 export dataset with completed audience export run",
   "Export completes; dataset shows rows for expected segment members",
   None,None),
  ("Federated Audience Composition",
   "Understand when to use FAC vs native RTCDP segmentation",
   "Review FAC overview; sketch 1-2 scenarios where FAC is a better fit than native segments",
   "FAC scenario notes with source systems, logic, and RTCDP usage",
   "Can explain what stays in FAC vs what is done natively in RTCDP segments",
   None,None),
  ("Flexible Audience Evaluation",
   "Understand FAE concepts and when to enable it",
   "Review FAE guide; create a prioritised list of candidate segments for FAE with rationale",
   "Prioritised FAE candidate list with tradeoffs documented",
   "Tradeoffs (control, cost, latency) are clearly articulated for each candidate",
   None,None),
  ("TTL and Data Retention",
   "Understand how dataset TTL impacts available lookback windows for segments",
   "Review TTL settings for 3-5 key datasets; map each to relevant segment lookback windows",
   "Mapping: segments vs datasets vs TTL settings",
   "No segment requires data older than its source dataset retention period",
   None,None),
  ("Segment and Profile Guardrails",
   "Understand default RTCDP Profile and segmentation guardrails",
   "Review guardrail documentation; estimate your profile counts, event volumes, and segment numbers against the guardrails",
   "Guardrail fit assessment with any identified risks",
   "Risks are identified where projected volumes approach or exceed limits",
   None,None),
],
5: [
  ("Destinations Overview",
   "Understand destination types and the activation lifecycle",
   "Explore Destinations Catalog and review all destination categories (Ad, Email, Cloud, Edge, Custom)",
   "Notes on each destination type and its primary use case",
   "Can explain online vs offline vs edge vs custom destinations and when to use each",
   "Destination Overview","6 min"),
  ("Connect to a Destination",
   "Connect RTCDP to an ad or marketing platform",
   "Configure an advertising destination from the Destinations catalog; complete the connection setup",
   "One configured destination with Connection status Active",
   "Destination appears under Browse with Connection status = Active",
   "Connect to destinations","4 min"),
  ("Activate Profiles and Audiences",
   "Activate profiles and audiences to a destination",
   "Create or choose a destination, select segments, configure identity and attribute mapping",
   "Destination with active segments and completed identity mappings",
   "IDs and traits mapped to expected fields; activation run succeeds",
   "Activate profiles and audiences to a destination","4 min"),
  ("Export Dataset via Cloud Storage",
   "Export datasets directly to cloud storage for downstream use",
   "Configure a cloud storage destination and set up a dataset export dataflow; run an export",
   "Files in cloud storage (CSV, Parquet, or JSON) at expected location",
   "File appears with correct schema and row count",
   "Exporting Datasets Using Cloud Storage Destinations","4 min"),
  ("Configure Azure Blob Storage Destination",
   "Set up Azure Blob as a cloud storage destination",
   "Create Azure Blob destination with connection string and container path; save and test export",
   "Working Azure Blob destination with test export file visible",
   "Test file is visible in the correct container and path with expected data",
   "Configuring Azure Blob Storage as a Destination","6 min"),
  ("Adobe Target and Custom Personalization",
   "Use RTCDP audiences with Target and custom personalization destinations",
   "Configure Adobe Target destination, map identity and traits, activate a test segment",
   "Target destination with at least one active segment",
   "Test profile qualifies on edge and attributes are available in Target",
   "Using RTCDP with Adobe Target and Custom Personalization","6 min"),
  ("Google Customer Match",
   "Activate audiences to Google Customer Match",
   "Configure Google Customer Match destination and assign RTCDP segments",
   "Google Customer Match destination with active audiences",
   "Audience appears in Google as a Customer Match list and begins populating",
   "Integrate Google Customer Match","3 min"),
  ("Marketo Destination",
   "Send RTCDP audiences to Marketo for email and engagement campaigns",
   "Configure Marketo Engage destination, map identities and attributes, activate a segment",
   "Marketo destination with at least one active audience",
   "Static or smart list in Marketo contains expected profiles",
   "Configure the Marketo Engage destination","6 min"),
  ("Social Destinations",
   "Connect RTCDP to social ad platforms (LinkedIn, Facebook)",
   "Configure a social destination, map IDs and attributes, activate test audiences",
   "Configured social destination with mapped identities and active segments",
   "Audience is visible in the social platform and begins filling",
   "Configure a social destination","4 min"),
  ("Activate to Non-Adobe Applications",
   "Understand activation patterns for non-Adobe tools via HTTP API, Kinesis, or Event Hubs",
   "Review activation patterns; draft a design for activating an audience to a non-Adobe endpoint",
   "Design document: audience, destination type (file vs streaming), endpoint details",
   "Use case is mapped to a feasible catalog destination type",
   "Activate data to non-Adobe applications webinar","43 min"),
  ("Server-Side Event Forwarding",
   "Configure Server-Side Event Forwarding for real-time data distribution",
   "Configure a server-side event forwarding rule; test forwarding to a test endpoint",
   "Implemented server-side event forwarding with successful test",
   "Event forwarding confirmed to test account or endpoint",
   "RT-CDP Connections: Server-Side Event Forwarding","18 min"),
],
6: [
  ("Monitoring Dashboard Overview",
   "Understand the monitoring dashboard and what it covers (ingestion, profiles, audiences, destinations)",
   "Log in to AEP and explore all monitoring dashboard tabs",
   "Familiarity with the monitoring dashboard and its main sections",
   "Can explain the monitoring dashboard and navigate to each section",
   None,None),
  ("Streaming Ingestion Monitoring",
   "Verify streaming connections and monitor near real-time data flows",
   "Open Monitoring Streaming end-to-end; review events per second and last event time",
   "Streaming monitoring familiarity",
   "Can point to where to see events per second and last event time for a streaming source",
   None,None),
  ("Batch Ingestion Monitoring",
   "Understand batch run details, error logs, and record counts",
   "Open Monitoring Batch end-to-end; locate error logs, total record counts, and field-level error details",
   "Batch monitoring familiarity",
   "Can locate error logs, total and failed record counts, and field-level error details",
   None,None),
  ("Dataflows to Data Lake",
   "Monitor dataflows landing data into the Data Lake",
   "Open Monitoring Dashboard Data Lake tab; review latest dataflow status, duration, and errors",
   "Data Lake dataflow monitoring familiarity",
   "Can explain whether the latest dataflow succeeded and identify errors or warnings",
   None,None),
  ("Profile Dataflow Monitoring",
   "Track profile ingestion and profile update success and failure",
   "Check Profile ingestion under Streaming end-to-end tab; identify profiles updated count",
   "Profile dataflow monitoring familiarity",
   "Can show where to see profiles updated and identify if updates are failing",
   None,None),
  ("Segment Job Monitoring",
   "Monitor segmentation runs and interpret evaluation metrics",
   "Open a segment, browse Segment Jobs, and review the latest run details",
   "Segmentation monitoring familiarity",
   "Can identify last run time, duration, profile counts, and whether the segment run completed successfully",
   "Monitoring Data Ingestion","6 min"),
  ("Destination Activation Monitoring",
   "Track export and activation jobs to destinations",
   "Open a configured destination, go to Activation Monitoring, and inspect job history",
   "Destination activation monitoring familiarity",
   "Can identify last activation run, status, number of records exported, and locate error messages",
   None,None),
  ("Segment Activation Monitoring",
   "Monitor and interpret the success of segment activation to destinations",
   "Select a destination with active activations, open the Monitoring view, review job results and counts",
   "Segment activation monitoring familiarity",
   "Can identify latest run status, exported counts, and locate error details",
   "Monitoring the success of segment activation","9 min"),
  ("Data Monitoring Overview",
   "Use AEP monitoring capabilities holistically to track ingestion, processing, and activation health",
   "Explore all workspaces; adjust filters and time ranges; inspect issues and trends across ingestion and activation",
   "Data monitoring familiarity across all workspaces",
   "Can explain what each monitoring view is for and where to look for issues",
   "Monitor Data Ingestion","14 min"),
],
7: [
  ("Federated Audience Composition Deep Dive",
   "Understand FAC capabilities, the challenges it solves, and its supported use cases",
   "Review FAC overview; identify 2-3 scenarios where FAC is the right approach vs native RTCDP",
   "FAC scenario notes with use case mapping",
   "Can explain FAC architecture, key capabilities, and when to recommend it",
   None,"215 min total"),
  ("AI Assistant in Experience Platform",
   "Learn to use AI Assistant across AEP, RTCDP, CJA, and AJO",
   "Review AI Assistant capabilities, trust considerations, and demo available features",
   "Notes on AI Assistant capabilities and known limitations",
   "Can demonstrate AI Assistant use cases in at least one AEP product",
   None,"68 min total"),
  ("Product Support Agent",
   "Use Product Support Agent to diagnose and escalate product issues faster",
   "Review Product Support Agent capabilities; practice a simulated troubleshooting scenario",
   "Product Support Agent familiarity",
   "Can describe how Product Support Agent helps diagnose issues and manage support cases",
   None,"57 min"),
  ("Customer AI - Overview and Model Setup",
   "Understand Customer AI propensity scoring and model development",
   "Review Customer AI workflow; set up a model with data prerequisites and define an outcome",
   "Customer AI model configuration notes",
   "Can define Customer AI, describe data prerequisites, and walk through model setup steps",
   None,None),
  ("Computed Attributes",
   "Understand how computed attributes summarise profile behaviour for segmentation and activation",
   "Review computed attributes documentation; identify 2-3 use cases where they add value",
   "Computed attribute definition with use case",
   "Can explain what a computed attribute is and a relevant use case in RTCDP or AJO",
   None,"60 min"),
  ("Look-Alike Audiences",
   "Understand RTCDP AI and ML-powered Look-Alike Audiences",
   "Review Look-Alike Audiences workflow through a demo; understand how it complements RTCDP segments",
   "Notes on Look-Alike Audiences feature and positioning",
   "Can explain what look-alike modelling does and how it integrates with RTCDP",
   None,"60 min"),
  ("Audience Portal and Composition",
   "Understand Audience Portal and Audience Composer features",
   "Review documentation; identify use cases and value for customers",
   "Summary of Audience Portal vs Audience Composition capabilities",
   "Can describe what Audience Portal is, how Audience Composer works, and 2-3 use cases",
   None,"60 min"),
  ("Use Case Playbooks",
   "Understand Use Case Playbooks as pre-packaged industry workflows in AEP",
   "Review Use Case Playbooks overview; identify 1-2 playbooks relevant to your team",
   "2 relevant playbooks with use case mapping",
   "Can explain what a Use Case Playbook is and how it accelerates adoption",
   None,"22 min"),
  ("Partner Data Support in RTCDP",
   "Understand Partner Data capabilities, use cases, and positioning strategy",
   "Review Partner Data overview and technical documentation",
   "Notes on partner data use cases and key limitations",
   "Can describe the market challenges addressed, capabilities, and best practices",
   None,"60 min"),
  ("Audience Agent",
   "Understand Audience Agent and Journey Agent for B2B and B2C workflows",
   "Review Audience Agent capabilities; identify applicable workflows for your team",
   "Notes on Audience Agent use cases for B2B and B2C",
   "Can describe Audience Agent capabilities and distinguish B2B vs B2C workflows",
   None,"34 min"),
],
8: [
  ("Query Service for Data Validation",
   "Use Query Service to validate and explore ingested data",
   "Run validation SQL queries against ingested datasets; verify profile counts and segment membership",
   "Working validation queries with results and notes",
   "Can run a validation query; explain how to use Query Service for data debugging",
   None,None),
  ("Profile Qualification Debugging",
   "Diagnose why a profile does or does not qualify for a segment",
   "Use Profile UI and Query Service to check segment membership, evaluate conditions, trace identity resolution",
   "Debugging notes for a diagnosed profile qualification issue",
   "Can identify why a profile is not qualifying; check identity stitching and merge policy impact",
   None,None),
  ("Segment Evaluation Diagnostics",
   "Diagnose segment evaluation job failures and unexpected results",
   "Review segment job logs in Monitoring; use Query Service to validate counts; cross-reference with source data",
   "Root cause analysis for a segment evaluation anomaly",
   "Can trace a segment evaluation failure from the monitoring dashboard to source data",
   None,None),
  ("POC and Testing in Sandbox",
   "Validate implementations in QA or stage sandbox before promoting to production",
   "Set up a test scenario in a non-production sandbox; run ingestion, segmentation, and activation end to end",
   "POC validation checklist with test results for all three stages",
   "Can describe the end-to-end validation approach for a new RTCDP implementation",
   None,None),
  ("Real-Time Profile Qualification",
   "Verify that profiles qualify for segments in real time after a streaming event",
   "Trigger a streaming event; verify immediate profile update and segment qualification in Profile UI",
   "Real-time qualification validation notes",
   "Can demonstrate real-time qualification after a streaming event and explain expected latency",
   None,None),
],
9: [
  ("RTCDP Business Practitioner Certification",
   "Prepare for and attempt the RTCDP Business Practitioner certification",
   "Review the exam guide, complete all practice assessments, review key modules, and schedule the exam",
   "RTCDP Business Practitioner Certificate",
   "Certification exam passed",
   None,None),
],
}

# ── Analytics Track ────────────────────────────────────────────────────────────
ANALYTICS = {
1: [
  ("Introduction to Adobe Analytics",
   "Understand what Adobe Analytics is, its place in the Adobe ecosystem, and key use cases",
   "Log in to Adobe Analytics, explore the Workspace UI, navigate between report suites and projects",
   "2-3 business questions Adobe Analytics can answer for your organisation",
   "Can describe in plain language what Adobe Analytics does and how it differs from AEP reporting",
   None,None),
  ("Analytics Architecture and Data Flow",
   "Understand how data flows from web or app to Adobe Analytics and how it is processed",
   "Review the Analytics architecture diagram; map data flow from collection to report",
   "Annotated architecture diagram with collection, processing, and reporting stages labeled",
   "Can explain the end-to-end flow from a page event to a processed report",
   None,"9 min"),
  ("Report Suites and Data Governance",
   "Understand report suite structure and how it governs data collection and reporting",
   "Open Admin, review report suite settings, identify key variables (props, eVars, events), and check data retention settings",
   "Notes on report suite structure and 3-5 key configured variables",
   "Can explain what a report suite is, how it differs from a virtual report suite, and why governance matters",
   None,None),
  ("Workspace Navigation and Key Concepts",
   "Navigate Analysis Workspace and understand its core building blocks",
   "Open Workspace, create a new project, add a freeform table, apply a segment, and add a visualization",
   "Working Workspace project with at least one table and one chart",
   "Can navigate Workspace confidently; explain dimensions, metrics, segments, and date ranges",
   None,"10 min"),
  ("Dimensions, Metrics, and Segments Basics",
   "Understand the difference between dimensions, metrics, and segments and how they interact",
   "In Workspace, drag dimensions and metrics into a freeform table; apply built-in segments; observe how the data changes",
   "Notes on the difference between each concept with one example of each",
   "Can correctly identify a dimension, a metric, and a segment and explain how they combine in a report",
   None,None),
],
2: [
  ("Data Collection Overview",
   "Understand the methods available for collecting data into Adobe Analytics",
   "Review the implementation options: Web SDK, AppMeasurement, Server API; identify which your organisation uses",
   "Summary of data collection methods and your org's current approach",
   "Can distinguish Web SDK from AppMeasurement; explain why an organisation might choose each",
   None,None),
  ("Adobe Tags and Web SDK",
   "Understand how Adobe Tags (Launch) and Web SDK are used to deploy Analytics",
   "Open Adobe Tags in the Data Collection UI; review an existing property, rules, and extensions",
   "Notes on the Tags property structure: extensions, rules, data elements",
   "Can explain what a Tag rule does; describe how data flows from a browser event to Analytics",
   None,"11 min"),
  ("AppMeasurement Implementation",
   "Understand the legacy AppMeasurement JavaScript library and how it sets Analytics variables",
   "Review an existing AppMeasurement implementation; locate key variable assignments (eVars, props, events)",
   "Notes on at least 3 variable types and their current assignments in the implementation",
   "Can read AppMeasurement code and explain what data is being captured and why",
   None,None),
  ("Mobile SDK Implementation",
   "Understand how mobile apps send data to Adobe Analytics",
   "Review the Mobile SDK documentation; identify the key configuration steps for iOS or Android",
   "Implementation checklist: key steps for mobile Analytics collection",
   "Can describe the main differences between web and mobile data collection in Analytics",
   None,"7 min"),
  ("Data Layer Concepts",
   "Understand what a data layer is and why it matters for reliable Analytics implementation",
   "Review the data layer structure for a sample web property; identify which variables feed Analytics",
   "Data layer documentation: key events and variables mapped to Analytics variables",
   "Can explain what a data layer is and why it reduces implementation fragility",
   None,None),
],
3: [
  ("Freeform Table Analysis",
   "Use freeform tables to answer business questions in Workspace",
   "Build 3 freeform tables answering different questions: one dimension-based, one time-based, one with breakdowns",
   "3 working freeform tables with clear business questions answered",
   "Can build a freeform table from scratch; apply breakdowns; sort and filter rows",
   None,"8 min"),
  ("Visualizations",
   "Create and configure key visualizations in Workspace (bar, line, area, scatter)",
   "Add at least 4 visualization types to a Workspace project; configure each appropriately",
   "Workspace project with 4 different visualization types, each labeled and configured",
   "Can select the right visualization for a given question and configure its key settings",
   None,"6 min"),
  ("Flow Analysis",
   "Use Flow visualization to understand user paths through a website or app",
   "Create a Flow visualization from a key entry or exit point; expand paths to at least 3 steps",
   "Flow diagram showing top user paths from a significant entry point",
   "Can interpret a Flow diagram; identify the most common next steps and drop-off points",
   None,"5 min"),
  ("Fallout Analysis",
   "Use Fallout visualization to measure conversion and drop-off through a defined funnel",
   "Create a Fallout visualization for a key conversion funnel (for example: page view, add to cart, purchase)",
   "Fallout visualization with at least 3 steps and conversion rates between each",
   "Can interpret fallout rates; explain what drives drop-off; propose a hypothesis for improvement",
   None,"5 min"),
  ("Cohort Analysis",
   "Use cohort tables to understand retention and repeat behavior",
   "Create a cohort table using a return event; interpret the retention pattern",
   "Cohort table with retention rates for at least 4 cohorts",
   "Can explain what a cohort table measures and interpret the retention pattern it shows",
   None,"6 min"),
  ("Segment Comparison Panel",
   "Compare two audience segments across all key metrics simultaneously",
   "Create a Segment Comparison panel with two meaningful segments; review the top differentiating dimensions and metrics",
   "Segment Comparison panel with at least 2 key insights noted",
   "Can set up a Segment Comparison and articulate the top differences between the two segments",
   None,"5 min"),
],
4: [
  ("Segment Builder",
   "Build audience segments using the Analytics Segment Builder",
   "Open the Segment Builder; create 3 segments of increasing complexity: attribute-based, behavior-based, and sequential",
   "3 saved segments: attribute, behavior, and sequential",
   "Can build segments at all three levels; explain containers (hit, visit, visitor) and when to use each",
   None,"6 min"),
  ("Sequential Segments",
   "Build segments that require events to occur in a specific order",
   "Create a sequential segment (for example: viewed product page then completed checkout)",
   "1 sequential segment with verified logic",
   "Can explain what makes a segment sequential; describe THEN vs AND vs OR operators",
   None,"4 min"),
  ("Segment Containers",
   "Understand hit, visit, and visitor containers and how they change segment scope",
   "Create the same logical segment at hit, visit, and visitor level; compare the audience sizes",
   "Notes on how container level changes the audience count and why",
   "Can predict how changing container scope affects a segment's audience",
   None,None),
  ("Publishing Segments to Experience Cloud",
   "Share Analytics segments with other Adobe solutions via Experience Cloud publishing",
   "Publish a segment to the Experience Cloud; verify it appears in Audience Manager or AEP",
   "Published segment confirmed available in target product",
   "Can explain when to publish a segment and what happens after publishing",
   None,None),
],
5: [
  ("Calculated Metrics",
   "Create custom metrics by combining existing metrics and dimensions",
   "Build 3 calculated metrics: a ratio metric (conversion rate), a derived metric (revenue per visit), and a filtered metric",
   "3 saved calculated metrics with correct formulas",
   "Can build a calculated metric; explain the difference between a ratio and a derived metric",
   None,"7 min"),
  ("Attribution Models",
   "Understand attribution models and how they distribute credit for conversions",
   "Apply at least 3 attribution models (Last Touch, First Touch, Linear) to the same conversion metric; compare results",
   "Side-by-side comparison of 3 attribution models on one conversion metric",
   "Can explain how each model allocates credit; recommend the right model for a given business question",
   None,"9 min"),
  ("Algorithmic Attribution",
   "Understand Contribution Analysis and data-driven attribution in Analytics",
   "Run a Contribution Analysis on an anomaly; review which dimensions contributed most",
   "Contribution Analysis results with top 3 contributing dimensions noted",
   "Can interpret Contribution Analysis output and explain how it differs from rule-based attribution",
   None,"6 min"),
  ("Advanced Calculated Metrics",
   "Build complex calculated metrics using functions and segment-filtered metrics",
   "Create one function-based metric (using MEAN or STDEV) and one segment-filtered metric",
   "2 advanced calculated metrics saved and working",
   "Can use functions in the calculated metric builder; explain when to use a filtered vs unfiltered metric",
   None,None),
],
6: [
  ("Admin Console Overview",
   "Understand the Analytics Admin Console and key configuration areas",
   "Open Admin, review: report suites, user management, data governance, and processing rules",
   "Admin Console map: what is in each section and who is responsible",
   "Can navigate the Admin Console and explain what each major section controls",
   None,None),
  ("Processing Rules",
   "Use Processing Rules to manipulate data as it flows into Analytics",
   "Create a processing rule that copies a query string parameter into an eVar; test with a hit",
   "1 processing rule created and confirmed working",
   "Can explain what processing rules do and when to use them vs data layer modifications",
   None,"5 min"),
  ("VISTA Rules",
   "Understand VISTA rules for advanced server-side data manipulation",
   "Review a VISTA rule example; document what it does and why a processing rule could not achieve the same outcome",
   "Notes on VISTA vs processing rules with a clear example",
   "Can explain when a VISTA rule is necessary and how it differs from a processing rule",
   None,None),
  ("User and Permission Management",
   "Manage Analytics user access and product profiles",
   "Open Adobe Admin Console, create a product profile for Analytics with defined permissions; add a test user",
   "Product profile created with appropriate permissions",
   "Can set up a product profile, assign permissions, and add users",
   None,None),
  ("Data Governance and Privacy",
   "Apply data governance and privacy controls in Adobe Analytics",
   "Review data labeling options in Analytics; apply labels to 3 variables based on data classification",
   "3 variables labeled with correct data classification types",
   "Can explain what GDPR data labels mean in Analytics and how labeling enables privacy request automation",
   None,None),
],
7: [
  ("Customer Journey Analytics Overview",
   "Understand what Customer Journey Analytics is and how it differs from Adobe Analytics",
   "Review CJA documentation; list 5 capabilities CJA offers that traditional Analytics does not",
   "Comparison table: CJA vs Adobe Analytics, 5 key differences",
   "Can explain the core architectural differences between CJA and Adobe Analytics",
   None,"12 min"),
  ("Connections in CJA",
   "Create a CJA Connection linking AEP datasets to a CJA workspace",
   "Create a Connection in CJA using at least one AEP dataset; configure the person ID and date field",
   "Working CJA Connection with at least one dataset configured",
   "Can explain what a Connection is; set up a Connection with correct person ID mapping",
   None,"8 min"),
  ("Data Views in CJA",
   "Configure a Data View to define how data from a Connection is exposed in Workspace",
   "Create a Data View; add components (dimensions, metrics); configure attribution and persistence for 3 components",
   "Working Data View with at least 5 components configured",
   "Can explain what a Data View is; configure component persistence and attribution settings",
   None,"10 min"),
  ("Workspace in CJA",
   "Use Analysis Workspace in CJA for cross-channel analysis",
   "Create a CJA Workspace project using your Data View; build a cross-channel freeform table and a Flow visualization",
   "CJA Workspace project with cross-channel analysis",
   "Can navigate CJA Workspace; identify where CJA analysis differs from traditional Analytics",
   None,"9 min"),
  ("Cross-Channel Attribution in CJA",
   "Understand and configure cross-channel attribution in CJA using stitching and the Attribution panel",
   "Configure field-based stitching on a Connection; apply 3 attribution models in the Attribution panel",
   "Stitching configured; Attribution panel showing 3 model comparison",
   "Can explain field-based stitching; interpret cross-channel attribution results",
   None,"8 min"),
],
8: [
  ("Data Warehouse",
   "Use Data Warehouse for large-scale, customised data extracts",
   "Create a Data Warehouse request with custom dimensions and metrics; schedule delivery to cloud storage",
   "Scheduled Data Warehouse report delivering to cloud storage",
   "Can explain when to use Data Warehouse vs Workspace; create and schedule a request",
   None,"6 min"),
  ("Data Feeds",
   "Understand Data Feeds for raw hit-level data export",
   "Review Data Feed configuration; identify the key files in a feed delivery and their structure",
   "Notes on Data Feed file structure: lookup files, hit data, metadata",
   "Can explain what a Data Feed is; describe the difference between a feed and a Data Warehouse report",
   None,None),
  ("Analytics Reporting API",
   "Access Analytics data programmatically via the Reporting API",
   "Use the Analytics 2.0 API to run a simple dimensions and metrics report; review the response structure",
   "Working API call with documented response structure",
   "Can authenticate to the Analytics API; construct a basic report request; interpret the response",
   None,"7 min"),
  ("Query Service Integration with Analytics",
   "Use AEP Query Service to analyse Analytics data stored in the Data Lake",
   "Run a SQL query against Analytics Experience Event data in the Data Lake; join with a profile dataset",
   "Working Query Service query joining Analytics and profile data",
   "Can query Analytics data in the Data Lake; explain how it differs from a Workspace report",
   None,None),
],
9: [
  ("Adobe Analytics Business Practitioner Certification",
   "Prepare for and attempt the Adobe Analytics Business Practitioner certification",
   "Review the exam guide, complete all practice assessments, review key modules, and schedule the exam",
   "Adobe Analytics Business Practitioner Certificate",
   "Certification exam passed",
   None,None),
],
}

EL_URLS_RTCDP = {
(1,1):"https://experienceleague.adobe.com/docs/platform-learn/tutorials/intro-to-platform/a-customer-experience-powered-by-experience-platform.html",
(1,2):"https://experienceleague.adobe.com/docs/platform-learn/tutorials/intro-to-platform/overview.html",
(1,3):"https://experienceleague.adobe.com/docs/platform-learn/tutorials/intro-to-platform/basic-architecture.html",
(1,4):"https://experienceleague.adobe.com/en/docs/experience-platform/landing/platform-apis/api-authentication",
(1,5):"https://experienceleague.adobe.com/en/docs/experience-platform/sandbox/home",
(1,6):"https://experienceleague.adobe.com/en/docs/experience-platform/rtcdp/intro/rtcdp-intro/overview",
(1,7):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/sources/overview",
(1,8):"https://experienceleague.adobe.com/en/docs/experience-platform/data-governance/home",
(1,9):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/profiles/understanding-the-real-time-customer-profile",
(1,10):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/audiences/audience-builder/create-audiences",
(1,11):"https://experienceleague.adobe.com/en/docs/experience-platform/query/home",
(2,1):"https://experienceleague.adobe.com/docs/platform-learn/tutorials/sources/ingest-data-from-adobe-analytics.html",
(2,2):"https://experienceleague.adobe.com/docs/platform-learn/tutorials/sources/ingest-data-from-aam.html",
(2,3):"https://experienceleague.adobe.com/docs/platform-learn/tutorials/sources/ingest-data-from-cloud-storage.html",
(2,4):"https://experienceleague.adobe.com/docs/platform-learn/tutorials/sources/ingest-data-from-crm.html",
(2,5):"https://experienceleague.adobe.com/docs/platform-learn/tutorials/sources/ingest-data-from-databases.html",
(2,6):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/identities/understanding-identity-and-identity-graphs",
(2,7):"https://experienceleague.adobe.com/en/docs/experience-platform/identity/home",
(3,1):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/profiles/understanding-the-real-time-customer-profile",
(3,2):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/profiles/overview-diagram",
(3,3):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/profiles/bring-data-into-the-real-time-customer-profile",
(3,4):"https://experienceleague.adobe.com/en/docs/experience-platform/profile/ui/profile-customization",
(3,5):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/profiles/view-account-profiles",
(3,6):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/profiles/create-merge-policies",
(3,7):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/profiles/union-schemas-overview",
(4,1):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/audiences/audience-builder/audience-rule-builder-overview",
(4,2):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/audiences/audience-builder/audience-rule-builder-overview",
(4,3):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/audiences/audience-builder/create-audiences",
(4,4):"https://experienceleague.adobe.com/en/docs/experience-platform/segmentation/home",
(4,5):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/audiences/audience-builder/create-content-based-audiences",
(4,6):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/audiences/audience-builder/create-conversion-audiences",
(4,7):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/audiences/audience-builder/create-audiences-from-existing-audiences",
(4,8):"https://experienceleague.adobe.com/en/docs/experience-platform/segmentation/tutorials/create-a-dynamic-segment",
(4,9):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/audiences/audience-builder/create-sequential-audiences",
(4,10):"https://experienceleague.adobe.com/en/docs/experience-platform/segmentation/tutorials/multi-entity-segmentation",
(4,11):"https://experienceleague.adobe.com/en/docs/experience-platform/rtcdp/segmentation/b2b",
(4,12):"https://experienceleague.adobe.com/en/docs/experience-platform/segmentation/tutorials/evaluate-a-segment",
(4,13):"https://experienceleague.adobe.com/en/docs/experience-platform/segmentation/tutorials/create-a-segment",
(4,14):"https://experienceleague.adobe.com/en/docs/experience-platform/segmentation/ui/audience-portal",
(4,15):"https://experienceleague.adobe.com/en/docs/experience-platform/segmentation/ui/audience-portal#flexible-audience-evaluation",
(4,16):"https://experienceleague.adobe.com/en/docs/experience-platform/catalog/datasets/experience-event-dataset-retention-ttl-guide",
(4,17):"https://experienceleague.adobe.com/en/docs/experience-platform/profile/guardrails",
(5,1):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/destinations/understanding-destinations",
(5,2):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/destinations/connecting-to-destinations",
(5,3):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/destinations/activate-profiles-and-segments-to-a-destination",
(5,4):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/destinations/configure-dataset-export-destination",
(5,5):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/destinations/configure-the-azure-blob-destination",
(5,6):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/destinations/target/next-hit-personalization",
(5,7):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/destinations/integrate-with-google-customer-match",
(5,8):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/destinations/configure-the-marketo-destination",
(5,9):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/destinations/configure-a-social-destination",
(5,10):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/destinations/activate-data-to-non-adobe-applications",
(5,11):"https://experienceleague.adobe.com/en/docs/experience-platform/tags/event-forwarding/overview",
(6,1):"https://experienceleague.adobe.com/en/docs/experience-platform/dataflows/ui/monitor",
(6,2):"https://experienceleague.adobe.com/en/docs/experience-platform/ingestion/quality/monitor-data-ingestion",
(6,3):"https://experienceleague.adobe.com/en/docs/experience-platform/ingestion/quality/monitor-data-ingestion",
(6,4):"https://experienceleague.adobe.com/en/docs/experience-platform/dataflows/ui/monitor-sources",
(6,5):"https://experienceleague.adobe.com/en/docs/experience-platform/dataflows/ui/monitor-streaming-profile",
(6,6):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/monitoring/monitoring-dashboard",
(6,7):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/monitoring/monitoring-dashboard",
(6,8):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/monitoring/monitoring-the-success-of-segment-activation",
(6,9):"https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/monitoring/data-monitoring",
(7,1):"https://experienceleague.adobe.com/en/docs/experience-platform/federated-audience-composition/home",
(7,2):"https://experienceleague.adobe.com/en/docs/experience-platform/ai-assistant/home",
(7,3):"https://experienceleague.adobe.com/en/docs/experience-platform/ai-assistant/home",
(7,4):"https://experienceleague.adobe.com/en/docs/experience-platform/intelligent-services/customer-ai/overview",
(7,5):"https://experienceleague.adobe.com/en/docs/experience-platform/profile/computed-attributes/overview",
(7,6):"https://experienceleague.adobe.com/en/docs/experience-platform/rtcdp/segmentation/customer-ai",
(7,7):"https://experienceleague.adobe.com/en/docs/experience-platform/segmentation/ui/audience-portal",
(7,8):"https://experienceleague.adobe.com/en/docs/experience-platform/use-case-playbooks/playbooks/overview",
(7,9):"https://experienceleague.adobe.com/en/docs/experience-platform/rtcdp/partner-data/prospecting",
(7,10):"https://experienceleague.adobe.com/en/docs/experience-platform/rtcdp/ai-customer-data-management/audience-agent",
(8,1):"https://experienceleague.adobe.com/en/docs/experience-platform/query/home",
(8,2):"https://experienceleague.adobe.com/en/docs/experience-platform/profile/troubleshooting",
(8,3):"https://experienceleague.adobe.com/en/docs/experience-platform/segmentation/troubleshooting",
(8,4):"https://experienceleague.adobe.com/en/docs/experience-platform/sandbox/home",
(8,5):"https://experienceleague.adobe.com/en/docs/experience-platform/profile/home",
(9,1):"https://experienceleague.adobe.com/en/docs/certification/program/technical-certifications/aep/aq-rtcdp-p-business-practitioner",
}

EL_URLS_ANALYTICS = {
(1,1):"https://experienceleague.adobe.com/en/docs/analytics/analyze/home",
(1,2):"https://experienceleague.adobe.com/en/docs/analytics/admin/admin-overview/analytics-overview",
(1,3):"https://experienceleague.adobe.com/en/docs/analytics/admin/admin-tools/report-suite/report-suites-admin",
(1,4):"https://experienceleague.adobe.com/en/docs/analytics-learn/tutorials/analysis-workspace/navigating-workspace-projects/understanding-the-workspace-interface",
(1,5):"https://experienceleague.adobe.com/en/docs/analytics/analyze/analysis-workspace/components/dimensions/t-breakdown-fa",
(2,1):"https://experienceleague.adobe.com/en/docs/analytics/implementation/home",
(2,2):"https://experienceleague.adobe.com/en/docs/analytics/implementation/aep-edge/overview",
(2,3):"https://experienceleague.adobe.com/en/docs/analytics/implementation/js/overview",
(2,4):"https://experienceleague.adobe.com/en/docs/analytics/implementation/aep-edge/mobile-sdk/overview",
(2,5):"https://experienceleague.adobe.com/en/docs/analytics/implementation/vars/overview",
(3,1):"https://experienceleague.adobe.com/en/docs/analytics-learn/tutorials/analysis-workspace/building-freeform-tables/using-freeform-tables",
(3,2):"https://experienceleague.adobe.com/en/docs/analytics/analyze/analysis-workspace/visualizations/freeform-analysis-visualizations",
(3,3):"https://experienceleague.adobe.com/en/docs/analytics/analyze/analysis-workspace/visualizations/flow/flow",
(3,4):"https://experienceleague.adobe.com/en/docs/analytics/analyze/analysis-workspace/visualizations/fallout/fallout-flow",
(3,5):"https://experienceleague.adobe.com/en/docs/analytics/analyze/analysis-workspace/visualizations/cohort-table/cohort-analysis",
(3,6):"https://experienceleague.adobe.com/en/docs/analytics/analyze/analysis-workspace/panels/segment-comparison/segment-comparison",
(4,1):"https://experienceleague.adobe.com/en/docs/analytics/components/segmentation/segmentation-workflow/seg-build",
(4,2):"https://experienceleague.adobe.com/en/docs/analytics/components/segmentation/segmentation-workflow/seg-sequential-build",
(4,3):"https://experienceleague.adobe.com/en/docs/analytics/components/segmentation/seg-overview",
(4,4):"https://experienceleague.adobe.com/en/docs/analytics/components/segmentation/segmentation-workflow/seg-publish",
(5,1):"https://experienceleague.adobe.com/en/docs/analytics/components/calculated-metrics/calcmetrics-reference/cm-overview",
(5,2):"https://experienceleague.adobe.com/en/docs/analytics/analyze/analysis-workspace/attribution/overview",
(5,3):"https://experienceleague.adobe.com/en/docs/analytics/analyze/analysis-workspace/panels/a4t-panel",
(5,4):"https://experienceleague.adobe.com/en/docs/analytics/components/calculated-metrics/calcmetrics-reference/cm-functions",
(6,1):"https://experienceleague.adobe.com/en/docs/analytics/admin/admin-tools/report-suite/edit-report-suite/general/general-acct-settings-admin",
(6,2):"https://experienceleague.adobe.com/en/docs/analytics/admin/admin-tools/manage-report-suites/edit-report-suite/general/processing-rules/processing-rules-tips",
(6,3):"https://experienceleague.adobe.com/en/docs/analytics/admin/admin-tools/manage-report-suites/edit-report-suite/general/processing-rules/processing-rules",
(6,4):"https://experienceleague.adobe.com/en/docs/analytics/admin/admin-overview/admin-permission-changes",
(6,5):"https://experienceleague.adobe.com/en/docs/analytics/admin/admin-tools/manage-report-suites/edit-report-suite/privacy-reporting",
(7,1):"https://experienceleague.adobe.com/en/docs/analytics-platform/using/cja-overview/cja-overview",
(7,2):"https://experienceleague.adobe.com/en/docs/analytics-platform/using/cja-connections/create-connection",
(7,3):"https://experienceleague.adobe.com/en/docs/analytics-platform/using/cja-dataviews/create-dataview",
(7,4):"https://experienceleague.adobe.com/en/docs/analytics-platform/using/cja-workspace/home",
(7,5):"https://experienceleague.adobe.com/en/docs/analytics-platform/using/stitching/overview",
(8,1):"https://experienceleague.adobe.com/en/docs/analytics/export/data-warehouse/data-warehouse",
(8,2):"https://experienceleague.adobe.com/en/docs/analytics/export/analytics-data-feed/data-feed-overview",
(8,3):"https://developer.adobe.com/analytics-apis/docs/2.0/",
(8,4):"https://experienceleague.adobe.com/en/docs/experience-platform/query/home",
(9,1):"https://experienceleague.adobe.com/en/docs/certification/program/technical-certifications/aa/aa-p-business",
}

conn = psycopg2.connect(DB)
cur = conn.cursor()

# Add track column if not exists
cur.execute("ALTER TABLE curriculum_topics ADD COLUMN IF NOT EXISTS track VARCHAR(50) DEFAULT 'rtcdp'")
cur.execute("UPDATE curriculum_topics SET track='rtcdp' WHERE track IS NULL")

# Rebuild RTCDP track
cur.execute("DELETE FROM curriculum_topics WHERE track='rtcdp'")
rtcdp_count = 0
for module_id, topics in RTCDP.items():
    for order, t in enumerate(topics, 1):
        title,obj,act,out,chk,vid,dur = t
        el_url = EL_URLS_RTCDP.get((module_id, order))
        cur.execute(
            "INSERT INTO curriculum_topics (module_id,topic_order,title,objective,activity,output,checkpoint,video_title,video_duration,track,el_url) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,'rtcdp',%s)",
            (module_id,order,title,obj,act,out,chk,vid,dur,el_url)
        )
        rtcdp_count += 1

# Seed Analytics track
cur.execute("DELETE FROM curriculum_topics WHERE track='analytics'")
analytics_count = 0
for module_id, topics in ANALYTICS.items():
    for order, t in enumerate(topics, 1):
        title,obj,act,out,chk,vid,dur = t
        el_url = EL_URLS_ANALYTICS.get((module_id, order))
        cur.execute(
            "INSERT INTO curriculum_topics (module_id,topic_order,title,objective,activity,output,checkpoint,video_title,video_duration,track,el_url) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,'analytics',%s)",
            (module_id,order,title,obj,act,out,chk,vid,dur,el_url)
        )
        analytics_count += 1

conn.commit()
cur.close()
conn.close()

print(f"RTCDP track: {rtcdp_count} topics across {len(RTCDP)} modules")
print(f"Analytics track: {analytics_count} topics across {len(ANALYTICS)} modules")
print(f"Total: {rtcdp_count + analytics_count} topics")
for mid,topics in RTCDP.items():
    print(f"  RTCDP M{mid}: {len(topics)}")
for mid,topics in ANALYTICS.items():
    print(f"  Analytics M{mid}: {len(topics)}")
